baseURL: "https://bkci.net"
languageCode: "zh-cn"
title: "è“é²¸æŒç»­é›†æˆå¹³å°"
theme: hugo-profile

Menus:
  main:
    - identifier: document
      name: æ–‡æ¡£ä¸­å¿ƒ
      title: æ–‡æ¡£ä¸­å¿ƒ
      url: https://docs.bkci.net
      weight: 1

    - identifier: bk
      name: è“é²¸å®˜ç½‘
      title: äº†è§£æ›´å¤šè“é²¸äº§å“
      url: https://bk.tencent.com
      weight: 2
      
params:
  title: "è“é²¸æŒç»­é›†æˆå¹³å°"
  description: ä¸€ä¸ªå…è´¹å¼€æºçš„æŒç»­é›†æˆç³»ç»Ÿ
  favicon: "/logo.png"
  useBootstrapCDN: false
  animate: true
  theme:
    disableThemeToggle: true
  color:
    backgroundColor: #FFFFFF

  hero:
    enable: true
    intro: "ä¸€ä¸ªå…è´¹å¹¶å¼€æºçš„CIæœåŠ¡"
    title: "è“é²¸æŒç»­é›†æˆå¹³å°"
    subtitle: "ç¼–è¯‘/æµ‹è¯•/éƒ¨ç½² ä½ çš„ä»£ç "
    content: "BKCIï¼ˆè“é²¸æŒç»­é›†æˆå¹³å°ï¼‰ åŠ©ä½ è‡ªåŠ¨åŒ–æ„å»º-æµ‹è¯•-å‘å¸ƒå·¥ä½œæµï¼ŒæŒç»­ã€å¿«é€Ÿã€é«˜è´¨é‡åœ°äº¤ä»˜ä½ çš„äº§å“ã€‚"
    image: /logo.png
    button:
      enable: true
      name: "Go to GitHub ğŸ‘‰"
      url: "https://github.com/Tencent/bk-ci"
      download: false
      newPage: true

  footer:
    recentPosts: false
